/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2017 (14.0.1000)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/
USE [master]
GO
/****** Object:  Database [WoWDb]    Script Date: 9/2/2019 12:33:03 PM ******/
CREATE DATABASE [WoWDb]
GO
ALTER DATABASE [WoWDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WoWDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WoWDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WoWDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WoWDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [WoWDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WoWDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WoWDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WoWDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WoWDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WoWDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WoWDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WoWDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WoWDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WoWDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [WoWDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WoWDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WoWDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WoWDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WoWDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WoWDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WoWDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WoWDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [WoWDb] SET  MULTI_USER 
GO
ALTER DATABASE [WoWDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WoWDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WoWDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WoWDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WoWDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'WoWDb', N'ON'
GO
ALTER DATABASE [WoWDb] SET QUERY_STORE = OFF
GO
USE [WoWDb]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [WoWDb]
GO
/****** Object:  Table [dbo].[AddOn]    Script Date: 9/2/2019 12:33:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AddOn](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](130) NULL,
	[Description] [text] NULL,
	[License] [nvarchar](50) NULL,
	[GitRepoUrl] [nvarchar](190) NULL,
	[AuthorId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_AddOn] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AddOnPayload]    Script Date: 9/2/2019 12:33:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AddOnPayload](
	[Id] [uniqueidentifier] NOT NULL,
	[PayloadDownloadUrl] [nvarchar](500) NOT NULL,
	[NumberOfDownloads] [int] NOT NULL,
	[AddOnVersionId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_AddOnPayload] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AddOnVersion]    Script Date: 9/2/2019 12:33:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AddOnVersion](
	[Id] [uniqueidentifier] NOT NULL,
	[MajorVersion] [int] NOT NULL,
	[MinorVersion] [int] NOT NULL,
	[PathVersion] [int] NOT NULL,
	[ReleaseNotes] [text] NOT NULL,
	[AddOnId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_AddOnVersion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 9/2/2019 12:33:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[Id] [uniqueidentifier] NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[WebsiteLink] [nvarchar](120) NULL,
	[DiscordLink] [nvarchar](120) NULL,
	[Email] [nvarchar](50) NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VersionComment]    Script Date: 9/2/2019 12:33:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VersionComment](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[AuthorId] [uniqueidentifier] NULL,
	[CommentText] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_VersionComment] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AddOn]  WITH CHECK ADD  CONSTRAINT [FK_AddOn_Author] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[Author] ([Id])
GO
ALTER TABLE [dbo].[AddOn] CHECK CONSTRAINT [FK_AddOn_Author]
GO
ALTER TABLE [dbo].[AddOnPayload]  WITH CHECK ADD  CONSTRAINT [FK_Payload_Version] FOREIGN KEY([AddOnVersionId])
REFERENCES [dbo].[AddOnVersion] ([Id])
GO
ALTER TABLE [dbo].[AddOnPayload] CHECK CONSTRAINT [FK_Payload_Version]
GO
ALTER TABLE [dbo].[AddOnVersion]  WITH CHECK ADD  CONSTRAINT [Fk_Version_AddOn] FOREIGN KEY([AddOnId])
REFERENCES [dbo].[AddOn] ([Id])
GO
ALTER TABLE [dbo].[AddOnVersion] CHECK CONSTRAINT [Fk_Version_AddOn]
GO
ALTER TABLE [dbo].[VersionComment]  WITH CHECK ADD  CONSTRAINT [FK_VersionComment_AddOnVersion] FOREIGN KEY([AuthorId])
REFERENCES [dbo].[AddOnVersion] ([Id])
GO
ALTER TABLE [dbo].[VersionComment] CHECK CONSTRAINT [FK_VersionComment_AddOnVersion]
GO
USE [master]
GO
ALTER DATABASE [WoWDb] SET  READ_WRITE 
GO
